#!/bin/bash
# Generated by dx-app-wizard.
set -e -x -o pipefail

dx download "$fastq_gz" -o reads.fq.gz
dx download "$fasta" -o subTag_ls.fasta

gunzip reads.fq.gz 
mkdir -p out/direct_map

line=$(wc -l < reads.fq)
mod=$((line%124))
file_sizes=$(((line-mod)/31))

pids=""

split -l $file_sizes reads.fq seg_

output_name="${fastq_gz_prefix}_${fasta_prefix}_map_w_tag.txt"

for i in seg_*
do
	fastq_mapping_w_tag_v1 subTag_ls.fasta "$i"  ${i/%/.txt}&
	pids="$pids $!"	
done

wait $pids

for i in seg_*.txt
do
	cat $i >> output.txt
done

paste -s -d+ output.txt | bc >$output_name
#upload results with dx-upload-all-outputs
mv $output_name out/direct_map/
dx-upload-all-outputs
